import { createTokens, persistSession } from "./token-manager";
import type { AuthResult, AuthSession, ConnectedAccount, UserProfile } from "./types";
import { validateAuthForm, validateEmail } from "./validation";
const accounts: ConnectedAccount[] = ["google", "github", "discord", "steam"].map((provider) => ({ provider, connected: false } as ConnectedAccount));
function profile(email: string, username?: string): UserProfile { const name = username || email.split("@")[0] || "player"; return { id: crypto.randomUUID(), email, username: name.toLowerCase(), displayName: name, bio: "Ready to play across NexaPlay.", country: "US", language: "en", emailVerified: false, themePreference: "system", notifications: { productUpdates: true, securityAlerts: true, friendActivity: false }, privacy: { profileVisibility: "friends", showOnlineStatus: true, showLibrary: false }, connectedAccounts: accounts }; }
function issue(user: UserProfile, rememberMe: boolean): AuthSession { const session = { user, tokens: createTokens(), rememberMe }; persistSession(session); return session; }
export async function loginWithEmail(email: string, password: string, rememberMe: boolean): Promise<AuthResult> { await new Promise((r) => setTimeout(r, 350)); const fieldErrors = validateAuthForm({ email, password }, ["email", "password"]); if (Object.keys(fieldErrors).length) return { ok: false, message: "Review the highlighted fields.", fieldErrors }; return { ok: true, message: "Welcome back to NexaPlay.", session: issue(profile(email), rememberMe) }; }
export async function registerWithEmail(values: { email: string; username: string; displayName: string; password: string; confirmPassword: string; rememberMe: boolean }): Promise<AuthResult> { await new Promise((r) => setTimeout(r, 450)); const fieldErrors = validateAuthForm({ email: values.email, username: values.username, displayName: values.displayName, password: values.password, confirmPassword: values.confirmPassword }, ["email", "username", "displayName", "password", "confirmPassword"]); if (Object.keys(fieldErrors).length) return { ok: false, message: "Review the highlighted fields.", fieldErrors }; return { ok: true, message: "Account created. Check your inbox to verify email.", session: issue(profile(values.email, values.username), values.rememberMe) }; }
export async function requestPasswordReset(email: string): Promise<AuthResult> { await new Promise((r) => setTimeout(r, 300)); const error = validateEmail(email); return error ? { ok: false, message: error, fieldErrors: { email: error } } : { ok: true, message: "Password reset instructions sent." }; }
export async function resetPassword(password: string, confirmPassword: string): Promise<AuthResult> { await new Promise((r) => setTimeout(r, 300)); const fieldErrors = validateAuthForm({ password, confirmPassword }, ["password", "confirmPassword"]); return Object.keys(fieldErrors).length ? { ok: false, message: "Choose a stronger password.", fieldErrors } : { ok: true, message: "Password updated. You can sign in now." }; }
