import { Badge, Button, Card, Checkbox, EmptyState, GlassCard, SearchInput, Skeleton, Tag } from "@/components/ui";
import { cn } from "@/lib/utils";
import { filterGroups, games, genres, recentSearches, searchSuggestions, sortOptions, storeNavItems, type StoreGame } from "@/lib/store/data";

const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export function StoreNavigation() {
  return <nav aria-label="Store" className="sticky top-20 z-20 -mx-2 overflow-x-auto py-2"><div className="flex min-w-max gap-2 rounded-full border border-white/10 bg-slate-950/75 p-1 backdrop-blur-xl">{storeNavItems.map((item, index) => <a key={item} href={index === 0 ? "/store" : `#${item.toLowerCase().replaceAll(" ", "-")}`} className={cn("rounded-full px-4 py-2 text-sm font-black transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200", index === 0 ? "bg-cyan-300 text-slate-950" : "text-slate-300 hover:bg-white/10 hover:text-white")}>{item}</a>)}</div></nav>;
}

export function StoreHero() {
  const featured = games.slice(0, 3);
  return <section className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]" aria-label="Featured carousel"><article className="relative min-h-[30rem] overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-cyan-300/20 via-violet-500/20 to-slate-950 p-6 shadow-2xl shadow-cyan-950/30 sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_22%,rgba(34,211,238,.38),transparent_18rem)]" /><div className="relative z-10 flex h-full max-w-2xl flex-col justify-end"><Badge>Featured premiere</Badge><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-6xl">Premium discovery for worlds worth getting lost in.</h1><p className="mt-5 text-lg leading-8 text-slate-300">Curated releases, intelligent discovery, expressive cards, accessible filters, and storefront states built on the NexaPlay design system.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button>Shop featured</Button><Button variant="secondary">Watch trailer</Button></div></div></article><div className="grid gap-4">{featured.map((game) => <GameCard key={game.id} game={game} compact />)}</div></section>;
}

export function StoreSearch() {
  return <GlassCard className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><label className="text-sm font-black uppercase tracking-wider text-slate-400" htmlFor="store-search">Search NexaPlay Store</label><SearchInput id="store-search" className="mt-3" placeholder="Search by title, genre, feature, or platform" aria-describedby="store-search-help" /><p id="store-search-help" className="mt-2 text-sm text-slate-500">Suggestions and recent searches are reusable data-driven states.</p><div className="mt-4 flex flex-wrap gap-2" aria-label="Search suggestions">{searchSuggestions.map((item) => <Tag key={item}>{item}</Tag>)}</div></div><div className="min-w-56 rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="font-black text-white">Recent searches</h2>{recentSearches.length ? <ul className="mt-3 space-y-2">{recentSearches.map((item) => <li key={item}><button className="w-full rounded-2xl px-3 py-2 text-left text-sm text-slate-300 transition hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200">{item}</button></li>)}</ul> : <EmptyState title="No recent searches" description="Search history will appear here." />}</div></GlassCard>;
}

export function FilterSortPanel() {
  return <aside className="space-y-5"><Card><h2 className="text-xl font-black text-white">Sort</h2><select aria-label="Sort games" className="mt-4 w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-cyan-300/60">{sortOptions.map((option) => <option key={option}>{option}</option>)}</select></Card><Card className="space-y-5"><h2 className="text-xl font-black text-white">Filters</h2>{filterGroups.map((group) => <fieldset key={group.title} className="border-t border-white/10 pt-4"><legend className="mb-3 text-sm font-black uppercase tracking-wider text-slate-400">{group.title}</legend><div className="space-y-2">{group.options.map((option) => <label key={option} className="flex items-center gap-3 text-sm text-slate-300"><Checkbox aria-label={`${group.title}: ${option}`} />{option}</label>)}</div></fieldset>)}</Card></aside>;
}

export function GameCard({ game, compact = false }: { game: StoreGame; compact?: boolean }) {
  const price = game.price === "Free" ? "Free" : currency.format(game.discount ? game.price * (1 - game.discount / 100) : game.price);
  return <article tabIndex={0} className={cn("group overflow-hidden rounded-3xl border border-white/10 bg-slate-950/70 shadow-[var(--shadow-panel)] transition duration-300 hover:-translate-y-1 hover:border-cyan-300/40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200", compact ? "grid grid-cols-[8rem_1fr]" : "") }><div className={cn("relative bg-gradient-to-br", game.cover, compact ? "min-h-36" : "h-56")}><div className="absolute left-4 top-4 grid size-14 place-items-center rounded-2xl border border-white/20 bg-black/30 text-lg font-black text-white backdrop-blur">{game.logo}</div>{game.discount ? <Badge tone="warning" className="absolute right-4 top-4">-{game.discount}%</Badge> : null}<button aria-label={`Add ${game.title} to wishlist`} className="absolute bottom-4 right-4 grid size-11 place-items-center rounded-full bg-black/40 text-xl text-white backdrop-blur transition hover:bg-cyan-300 hover:text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200">♡</button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-black text-white">{game.title}</h3><span className="rounded-full bg-emerald-300/15 px-2 py-1 text-xs font-black text-emerald-100">{game.rating}</span></div><div className="mt-3 flex flex-wrap gap-2">{game.tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}</div><div className="mt-4 flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-slate-500">Released {new Date(game.releaseDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</p><p className="mt-2 text-sm text-slate-400" aria-label={`Platforms: ${game.platforms.join(", ")}`}>{game.platforms.join(" · ")}</p></div><strong className="text-lg text-white">{price}</strong></div></div></article>;
}

export function GameSection({ id, title, description, items = games }: { id: string; title: string; description: string; items?: StoreGame[] }) {
  return <section id={id} className="scroll-mt-32" aria-labelledby={`${id}-title`}><div className="mb-5 flex items-end justify-between gap-4"><div><h2 id={`${id}-title`} className="text-2xl font-black text-white sm:text-3xl">{title}</h2><p className="mt-2 text-sm text-slate-400">{description}</p></div><Button variant="ghost">View all</Button></div><div className="grid gap-5 sm:grid-cols-2 2xl:grid-cols-3">{items.map((game) => <GameCard key={`${id}-${game.id}`} game={game} />)}</div></section>;
}

export function CategoryGrid() {
  return <section id="categories" className="scroll-mt-32"><h2 className="text-2xl font-black text-white sm:text-3xl">Popular categories</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{genres.map((genre, index) => <a key={genre} href={`#${genre.toLowerCase()}`} className="group rounded-3xl border border-white/10 bg-white/[0.04] p-5 transition hover:-translate-y-1 hover:border-cyan-300/40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200"><div className="mb-8 size-10 rounded-2xl bg-gradient-to-br from-cyan-300 to-violet-400 shadow-[var(--shadow-glow)]" /><h3 className="font-black text-white">{genre}</h3><p className="mt-2 text-sm text-slate-400">{12 + index * 7} curated titles</p></a>)}</div></section>;
}

export function StoreStates() {
  return <section className="grid gap-5 md:grid-cols-3" aria-label="Store states"><Card><Skeleton className="h-40" /><Skeleton className="mt-4 h-5 w-2/3" /><Skeleton className="mt-3 h-4 w-1/2" /></Card><EmptyState title="No results found" description="Try removing filters or searching for another game." /><EmptyState title="Something went wrong" description="Store content could not load. Retry keeps the state reusable." /></section>;
}
