"use client";
import Link from "next/link";
import { Avatar, Badge, Button, Card, EmptyState, GlassCard, LoadingState, Switch, Tag } from "@/components/ui";
import { useAuth } from "@/components/providers/auth-provider";
import type { UserProfile } from "@/lib/auth/types";
export function ProfileCard({ user }: { user: UserProfile }) { return <GlassCard className="hover-lift"><div className="flex items-start gap-4"><Avatar name={user.displayName} src={user.avatarUrl} className="size-16 text-xl" /><div><Badge tone={user.emailVerified ? "success" : "warning"}>{user.emailVerified ? "Verified" : "Email pending"}</Badge><h2 className="mt-3 text-2xl font-black text-white">{user.displayName}</h2><p className="text-sm text-cyan-100">@{user.username}</p><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">{user.bio}</p></div></div></GlassCard>; }
export function SettingsCard({ user }: { user: UserProfile }) { return <Card className="space-y-5"><h3 className="text-xl font-black text-white">Preferences</h3><div className="grid gap-3 sm:grid-cols-2"><Tag>Country: {user.country}</Tag><Tag>Language: {user.language}</Tag><Tag>Theme: {user.themePreference}</Tag><Tag>Privacy: {user.privacy.profileVisibility}</Tag></div><div className="space-y-3"><label className="flex items-center justify-between text-sm text-slate-300">Security alerts <Switch checked={user.notifications.securityAlerts} readOnly /></label><label className="flex items-center justify-between text-sm text-slate-300">Online status <Switch checked={user.privacy.showOnlineStatus} readOnly /></label></div></Card>; }
export function ConnectedAccounts({ user }: { user: UserProfile }) { return <Card><h3 className="text-xl font-black text-white">Connected accounts</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{user.connectedAccounts.map((account) => <div key={account.provider} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="font-bold capitalize text-white">{account.provider}</div><p className="text-sm text-slate-400">{account.connected ? account.handle : "Ready for OAuth adapter"}</p></div>)}</div></Card>; }
export function UserMenu() { const auth = useAuth(); if (auth.status === "loading") return <LoadingState label="Checking session" />; if (!auth.user) return <div className="flex items-center gap-3"><Link href="/login" className="rounded-full border border-white/10 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:border-cyan-300/50 hover:text-white">Sign in</Link><Link href="/register" className="rounded-full bg-cyan-300 px-4 py-2 text-sm font-black text-slate-950 shadow-[0_0_28px_rgba(34,211,238,0.28)] transition hover:bg-cyan-200">Join beta</Link></div>; return <div className="flex items-center gap-3"><Link href="/profile" className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-sm text-slate-200"><Avatar name={auth.user.displayName} src={auth.user.avatarUrl} /> {auth.user.displayName}</Link><Button variant="ghost" onClick={auth.logout}>Log out</Button></div>; }
export function ProfileDashboard() { const auth = useAuth(); if (auth.status === "loading") return <LoadingState label="Loading profile" />; if (!auth.user) return <EmptyState title="Sign in required" description="Protected profile architecture redirects here when a session is not available." />; return <section className="space-y-6"><ProfileCard user={auth.user} /><div className="grid gap-6 lg:grid-cols-2"><SettingsCard user={auth.user} /><ConnectedAccounts user={auth.user} /></div></section>; }
