"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button, Checkbox, Divider, Spinner } from "@/components/ui";
import { useAuth } from "@/components/providers/auth-provider";
import { Field, PasswordField } from "./form-fields";
import { SocialLoginButtons } from "./social-login-buttons";

type Errors = Record<string, string>;
function Notice({ message, tone }: { message: string; tone: "success" | "error" }) { return <p role="status" className={tone === "success" ? "rounded-2xl bg-emerald-300/10 p-3 text-sm text-emerald-100" : "rounded-2xl bg-rose-300/10 p-3 text-sm text-rose-100"}>{message}</p>; }
export function LoginForm() { const auth = useAuth(); const router = useRouter(); const [errors, setErrors] = useState<Errors>({}); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); async function onSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); const data = new FormData(e.currentTarget); const result = await auth.login(String(data.get("email") ?? ""), String(data.get("password") ?? ""), data.get("remember") === "on"); setLoading(false); setMessage(result.message); setErrors(result.ok ? {} : result.fieldErrors ?? {}); if (result.ok) router.push("/profile"); } return <form onSubmit={onSubmit} className="space-y-5" noValidate><SocialLoginButtons /><Divider /><Field name="email" label="Email" type="email" autoComplete="email" error={errors.email} /><PasswordField name="password" label="Password" autoComplete="current-password" error={errors.password} /><label className="flex items-center gap-2 text-sm text-slate-300"><Checkbox name="remember" /> Remember me on this device</label>{message && <Notice message={message} tone={Object.keys(errors).length ? "error" : "success"} />}<Button className="w-full" disabled={loading}>{loading && <Spinner className="mr-2" />}Sign in</Button><p className="text-center text-sm text-slate-400"><Link className="text-cyan-200" href="/forgot-password">Forgot password?</Link> · <Link className="text-cyan-200" href="/register">Create account</Link></p></form>; }
export function RegisterForm() { const auth = useAuth(); const router = useRouter(); const [errors, setErrors] = useState<Errors>({}); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); async function onSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); const data = new FormData(e.currentTarget); const result = await auth.register({ email: String(data.get("email") ?? ""), username: String(data.get("username") ?? ""), displayName: String(data.get("displayName") ?? ""), password: String(data.get("password") ?? ""), confirmPassword: String(data.get("confirmPassword") ?? ""), rememberMe: data.get("remember") === "on" }); setLoading(false); setMessage(result.message); setErrors(result.ok ? {} : result.fieldErrors ?? {}); if (result.ok) router.push("/verify-email"); } return <form onSubmit={onSubmit} className="space-y-5" noValidate><SocialLoginButtons /><Divider /><div className="grid gap-4 sm:grid-cols-2"><Field name="username" label="Username" autoComplete="username" error={errors.username} /><Field name="displayName" label="Display name" autoComplete="name" error={errors.displayName} /></div><Field name="email" label="Email" type="email" autoComplete="email" error={errors.email} /><PasswordField name="password" label="Password" autoComplete="new-password" error={errors.password} /><PasswordField name="confirmPassword" label="Confirm password" autoComplete="new-password" error={errors.confirmPassword} /><label className="flex items-center gap-2 text-sm text-slate-300"><Checkbox name="remember" defaultChecked /> Keep me signed in</label>{message && <Notice message={message} tone={Object.keys(errors).length ? "error" : "success"} />}<Button className="w-full" disabled={loading}>{loading && <Spinner className="mr-2" />}Create account</Button></form>; }
export function ForgotPasswordForm() { const auth = useAuth(); const [errors, setErrors] = useState<Errors>({}); const [message, setMessage] = useState(""); async function onSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const result = await auth.forgotPassword(String(data.get("email") ?? "")); setMessage(result.message); setErrors(result.ok ? {} : result.fieldErrors ?? {}); } return <form onSubmit={onSubmit} className="space-y-5" noValidate><Field name="email" label="Account email" type="email" error={errors.email} />{message && <Notice message={message} tone={Object.keys(errors).length ? "error" : "success"} />}<Button className="w-full">Send reset link</Button></form>; }
export function ResetPasswordForm() { const auth = useAuth(); const [errors, setErrors] = useState<Errors>({}); const [message, setMessage] = useState(""); async function onSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const result = await auth.resetPassword(String(data.get("password") ?? ""), String(data.get("confirmPassword") ?? "")); setMessage(result.message); setErrors(result.ok ? {} : result.fieldErrors ?? {}); } return <form onSubmit={onSubmit} className="space-y-5" noValidate><PasswordField name="password" label="New password" error={errors.password} /><PasswordField name="confirmPassword" label="Confirm new password" error={errors.confirmPassword} />{message && <Notice message={message} tone={Object.keys(errors).length ? "error" : "success"} />}<Button className="w-full">Update password</Button></form>; }
