"use client";

import { useId, useState, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type TextareaHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

type Variant = "primary" | "secondary" | "ghost" | "danger";
export function Button({ className, variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: Variant }) {
  const variants = { primary: "bg-cyan-300 text-slate-950 shadow-[var(--shadow-glow)] hover:bg-cyan-200", secondary: "border border-white/10 bg-white/10 text-white hover:border-cyan-300/40", ghost: "text-slate-200 hover:bg-white/10", danger: "bg-rose-400 text-white hover:bg-rose-300" };
  return <button className={cn("inline-flex min-h-11 items-center justify-center rounded-full px-5 py-2 text-sm font-black transition duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200 disabled:cursor-not-allowed disabled:opacity-50", variants[variant], className)} {...props} />;
}
export function IconButton({ variant = "secondary", className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: Variant }) { return <Button {...props} className={cn("size-11 px-0", className)} variant={variant} />; }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-3xl border border-white/10 bg-slate-950/60 p-6 shadow-[var(--shadow-panel)]", className)} {...props} />; }
export function GlassCard({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-3xl border border-white/10 bg-white/[0.06] p-6 shadow-[var(--shadow-panel)] backdrop-blur-2xl", className)} {...props} />; }
export function Badge({ className, tone = "cyan", ...props }: HTMLAttributes<HTMLSpanElement> & { tone?: "cyan" | "purple" | "success" | "warning" | "error" }) { const tones = { cyan: "bg-cyan-300/15 text-cyan-100 ring-cyan-300/30", purple: "bg-violet-300/15 text-violet-100 ring-violet-300/30", success: "bg-emerald-300/15 text-emerald-100 ring-emerald-300/30", warning: "bg-amber-300/15 text-amber-100 ring-amber-300/30", error: "bg-rose-300/15 text-rose-100 ring-rose-300/30" }; return <span className={cn("inline-flex rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ring-1", tones[tone], className)} {...props} />; }
export function Tag(props: HTMLAttributes<HTMLSpanElement>) { return <span className={cn("inline-flex rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold text-slate-300", props.className)} {...props} />; }
export function Divider(props: HTMLAttributes<HTMLHRElement>) { return <hr className={cn("border-0 border-t border-white/10", props.className)} {...props} />; }
export function Avatar({ name, src, className }: { name: string; src?: string; className?: string }) { return src ? <img src={src} alt={name} className={cn("size-10 rounded-full object-cover ring-2 ring-cyan-300/30", className)} /> : <span className={cn("grid size-10 place-items-center rounded-full bg-gradient-to-br from-cyan-300 to-violet-400 text-sm font-black text-slate-950", className)}>{name.slice(0,2).toUpperCase()}</span>; }
export function Spinner({ className }: { className?: string }) { return <span role="status" aria-label="Loading" className={cn("inline-block size-5 animate-spin rounded-full border-2 border-cyan-200 border-t-transparent", className)} />; }
export function Skeleton({ className }: { className?: string }) { return <span className={cn("block animate-pulse rounded-2xl bg-white/10", className)} />; }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="group relative inline-flex"><span>{children}</span><span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 z-[var(--z-tooltip)] mb-2 -translate-x-1/2 whitespace-nowrap rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-xs text-white opacity-0 shadow-xl transition group-hover:opacity-100 group-focus-within:opacity-100">{label}</span></span>; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-[var(--z-modal)] grid place-items-center bg-black/70 p-4 backdrop-blur" role="dialog" aria-modal="true" aria-labelledby="modal-title"><GlassCard className="w-full max-w-lg"><div className="flex items-center justify-between"><h2 id="modal-title" className="text-xl font-black text-white">{title}</h2><IconButton aria-label="Close modal" onClick={onClose}>×</IconButton></div><div className="mt-4">{children}</div></GlassCard></div>; }
export function Drawer({ open, children, onClose }: { open: boolean; children: ReactNode; onClose: () => void }) { return <aside className={cn("fixed right-0 top-0 z-[var(--z-drawer)] h-full w-full max-w-sm border-l border-white/10 bg-slate-950/95 p-6 shadow-2xl backdrop-blur-xl transition-transform", open ? "translate-x-0" : "translate-x-full")} aria-hidden={!open}><IconButton aria-label="Close drawer" onClick={onClose}>×</IconButton><div className="mt-6">{children}</div></aside>; }
export function Dropdown({ label, children }: { label: string; children: ReactNode }) { const [open,setOpen]=useState(false); return <div className="relative inline-block"><Button variant="secondary" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{label}</Button>{open && <div role="menu" className="absolute right-0 z-[var(--z-dropdown)] mt-2 min-w-48 rounded-2xl border border-white/10 bg-slate-950 p-2 shadow-2xl">{children}</div>}</div>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("min-h-11 w-full rounded-2xl border border-white/10 bg-white/5 px-4 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-cyan-300/60 focus:ring-4 focus:ring-cyan-300/10", props.className)} {...props} />; }
export function SearchInput(props: InputHTMLAttributes<HTMLInputElement>) { return <Input type="search" placeholder="Search" {...props} className={cn("pl-10", props.className)} />; }
export function TextArea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-28 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-cyan-300/60 focus:ring-4 focus:ring-cyan-300/10", props.className)} {...props} />; }
export function Checkbox(props: InputHTMLAttributes<HTMLInputElement>) { return <input type="checkbox" className={cn("size-5 rounded border-white/20 bg-white/10 accent-cyan-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200", props.className)} {...props} />; }
export function Switch({ checked, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <label className="inline-flex cursor-pointer items-center"><input type="checkbox" className="peer sr-only" checked={checked} {...props} /><span className="h-6 w-11 rounded-full bg-slate-700 p-1 transition peer-checked:bg-cyan-300"><span className="block size-4 rounded-full bg-white transition peer-checked:translate-x-5" /></span></label>; }
export function Radio(props: InputHTMLAttributes<HTMLInputElement>) { return <input type="radio" className={cn("size-5 border-white/20 bg-white/10 accent-violet-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-200", props.className)} {...props} />; }
export function Tabs({ tabs }: { tabs: { label: string; content: ReactNode }[] }) { const [active,setActive]=useState(0); const id=useId(); return <div><div role="tablist" className="flex gap-2 rounded-full border border-white/10 bg-white/5 p-1">{tabs.map((tab,i)=><button key={tab.label} id={`${id}-tab-${i}`} role="tab" aria-selected={active===i} aria-controls={`${id}-panel-${i}`} onClick={()=>setActive(i)} className={cn("rounded-full px-4 py-2 text-sm font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200", active===i ? "bg-cyan-300 text-slate-950" : "text-slate-300 hover:bg-white/10")}>{tab.label}</button>)}</div><div id={`${id}-panel-${active}`} role="tabpanel" aria-labelledby={`${id}-tab-${active}`} className="mt-4">{tabs[active]?.content}</div></div>; }
export function ProgressBar({ value }: { value: number }) { return <div role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} className="h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400 transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
export function Toast({ children }: { children: ReactNode }) { return <div role="status" className="fixed bottom-6 right-6 z-[var(--z-toast)] rounded-2xl border border-cyan-300/30 bg-slate-950/95 px-5 py-4 text-sm text-white shadow-[var(--shadow-glow)] backdrop-blur">{children}</div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <Card className="grid place-items-center py-12 text-center"><div className="size-12 rounded-2xl bg-cyan-300/10" /><h3 className="mt-4 text-lg font-black text-white">{title}</h3><p className="mt-2 max-w-sm text-sm text-slate-400">{description}</p></Card>; }
export function LoadingState({ label="Loading interface" }: { label?: string }) { return <Card className="space-y-4" aria-busy="true"><Spinner /><p className="text-sm text-slate-300">{label}</p><Skeleton className="h-4 w-2/3" /><Skeleton className="h-4 w-1/2" /></Card>; }
